name: Deploy Single WordPress container

on:
  push:
    paths:
      - 'wp-config.php'

env:
  RESOURCE_GROUP: Rg-DevOps-GWC-02
  ACR_LOGIN_SERVER: containerregistrywordpressgwc01.azurecr.io
  CONTAINER_NAME_PREFIX: container-wordpress-0
  STORAGE_ACCOUNT_NAME: saccountwordpressgwc01
  FILE_SHARE_NAME: wpcontent

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push WordPress container image
        run: |
          IMAGE_TAG="latest"
          docker build \
            --build-arg AUTH_KEY="${{ secrets.AUTH_KEY_SALT }}" \
            --build-arg SECURE_AUTH_KEY="${{ secrets.SECURE_AUTH_KEY_SALT }}" \
            --build-arg LOGGED_IN_KEY="${{ secrets.LOGGED_IN_KEY_SALT }}" \
            --build-arg NONCE_KEY="${{ secrets.NONCE_KEY_SALT }}" \
            --build-arg AUTH_SALT="${{ secrets.AUTH_SALT }}" \
            --build-arg SECURE_AUTH_SALT="${{ secrets.SECURE_AUTH_SALT }}" \
            --build-arg LOGGED_IN_SALT="${{ secrets.LOGGED_IN_SALT }}" \
            --build-arg NONCE_SALT="${{ secrets.NONCE_SALT }}" \
          -t ${{ env.ACR_LOGIN_SERVER }}/wordpress:$IMAGE_TAG .
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ env.ACR_LOGIN_SERVER }}/wordpress:$IMAGE_TAG

      - name: Deploy WordPress container to Azure Container Instances
        run: |
          IMAGE_TAG=${{ github.sha }}
          CONTAINER_NAME=${{ env.CONTAINER_NAME_PREFIX }}${{ github.run_number }}
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name $CONTAINER_NAME \
            --image ${{ env.ACR_LOGIN_SERVER }}/wordpress:$IMAGE_TAG \
            --cpu 1 \
            --memory 1.5 \
            --ports 443 \
            --ip-address Private \
            --os-type Linux \
            --subnet ${{ secrets.SUBNET_ID }} \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --azure-file-volume-account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --azure-file-volume-account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --volumes '[
              {
                "name": "wpcontent",
                "azureFile": {
                  "shareName": "'$FILE_SHARE_NAME'",
                  "storageAccountName": "'$STORAGE_ACCOUNT_NAME'",
                  "storageAccountKey": "'$STORAGE_ACCOUNT_KEY'"
                }
              },
              {
                "name": "certs",
                "azureFile": {
                  "shareName": "'$CERT_SHARE_NAME'",
                  "storageAccountName": "'$STORAGE_ACCOUNT_NAME'",
                  "storageAccountKey": "'$STORAGE_ACCOUNT_KEY'"
                }
              }
            ]' \
            --volume-mounts '[
              {
                "name": "wpcontent",
                "mountPath": "/var/www/html/wp-content"
              },
              {
              "name": "certs",
              "mountPath": "/certs"
              }
            ]' \
            --environment-variables \
                WORDPRESS_DB_HOST="${{ secrets.DB_HOST }}" \
                WORDPRESS_DB_NAME="${{ secrets.WORDPRESS_DB_NAME }}" \
                WORDPRESS_DB_USER="${{ secrets.DB_USER }}" \
                WORDPRESS_DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                EXT_DB_HOST="${{ secrets.DB_HOST }}" \
                EXT_DB_NAME="${{ secrets.EXT_DB_NAME }}" \
                EXT_DB_USER="${{ secrets.DB_USER }}" \
                EXT_DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                AUTH_KEY="${{ secrets.AUTH_KEY_SALT }}" \
                SECURE_AUTH_KEY="${{ secrets.SECURE_AUTH_KEY_SALT }}" \
                LOGGED_IN_KEY="${{ secrets.LOGGED_IN_KEY_SALT }}" \
                NONCE_KEY="${{ secrets.NONCE_KEY_SALT }}" \
                AUTH_SALT="${{ secrets.AUTH_SALT }}" \
                SECURE_AUTH_SALT="${{ secrets.SECURE_AUTH_SALT }}" \
                LOGGED_IN_SALT="${{ secrets.LOGGED_IN_SALT }}" \
                NONCE_SALT="${{ secrets.NONCE_SALT }}" \
                CBP_ENCRYPTION_KEY="${{ secrets.CBP_ENCRYPTION_KEY }}" \
                CBP_ENCRYPTION_IV="${{ secrets.CBP_ENCRYPTION_IV }}"
                CERT_SHARE_NAME = "${{ secrets.CERT_SHARE_NAME }}"
